language: python
python: 3.6
env:
  global:
    - ES_VERSION=6.3.1
    - ES_HOME="${TRAVIS_BUILD_DIR}/.deps/elasticsearch-${ES_VERSION}/"
  matrix:
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=py36
    - TOXENV=coverage
cache:
  directories:
    - $HOME/.cache/pip

before_install:
  - mkdir .deps
  - cd .deps
  - wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
  - tar -xvzf elasticsearch-${ES_VERSION}.tar.gz
  - cd -

install: pip install docutils tox
script: tox
