language: python
python: 3.6
service: elasticsearch
env:
  matrix:
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=py36
    - TOXENV=coverage
cache:
  directories:
    - $HOME/.cache/pip
install: pip install docutils tox
script: tox
